import Navbar from "@/components/Navbar";
import "./globals.css";
import PageTransition from "@/components/PageTransition";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <PageTransition>
               <Navbar />
               {children}
            </PageTransition>
         </body>
      </html>
   );
}
